version: '2'

services:
  mongodb:
    build: mongodb/
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - stack

  metabase:
    build: metabase/
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./data/metabase:/metabase-data
    networks:
      - stack
    depends_on:
      - mongodb

  importer:
    build: importer/
    environment:
      - IMPORT_RUN=false
      - MONGO_DATABASE=db
      - MONGO_COLLECTION=collection
    networks:
      - stack
    depends_on:
      - mongodb

networks:
  stack:
    driver: bridge
